config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :spaces, except: [:new, :edit, :update], param: :slug, shallow: true do
    resources :lists, except: [:index] do
      resources :tokens, except: [:index, :new, :show]
    end
  end
  root 'home#show'
  get ':slug', to: 'spaces#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true
  has_many :tokens, dependent: :nullify
end

app/models/list.rb
class List < ApplicationRecord
  has_many :tokens, dependent: :destroy
  belongs_to :space
end

app/models/space.rb
class Space < ApplicationRecord
  has_many :lists, dependent: :destroy

  before_create :set_slug

  def to_param
    slug
  end

  private

    def generate_slug
      array = []

      3.times { array << Faker::Creature::Animal.unique.name }
      Faker::UniqueGenerator.clear

      array.join('-')
    end

    def set_slug
      loop do
        self.slug = generate_slug
        break unless Space.where(slug: slug).exists?
      end
    end
end

app/models/token.rb
class Token < ApplicationRecord
  belongs_to :list
  belongs_to :category, optional: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_forgery_protection
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all

    respond_to do |format|
      format.html { render 'other/404' }
      format.json { render :index, status: :ok }
    end
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def edit
    @category = Category.find(params[:id])
  end

  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to lists_path, notice: 'Category created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render 'new' }
      end
    end
  end

  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to lists_path, notice: 'Successfully edited the category.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render 'edit' }
      end

    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'Category deleted.' }
      format.json { head :no_content }
    end
  end

  private

    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'home'

  def show
    @space = Space.new
    render 'home/show'
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  def index
    @lists = List.all
    @categories = Category.all
  end

  def show
    @groupedTokens = groupTokens(@list)
  end

  def new
    @space = Space.find_by slug: params[:space_slug]
    @list = List.new
  end

  def edit
  end

  def create
    @space = Space.find_by slug: params[:space_slug]
    @list = @space.lists.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to space_url(@list.space), notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_list
      @list = List.find(params[:id])
    end

    def list_params
      params.require(:list).permit(:name, :space_slug)
    end

    def groupTokens(list)
      result = {}

      list.tokens.each do |token|
        if token.category.nil?
          result['None'] = result['None'] || []
          result['None'].push token
        else
          result[token.category.name] = result[token.category.name] || []
          result[token.category.name].push token
        end
      end

      result
    end
end

app/controllers/spaces_controller.rb
class SpacesController < ApplicationController
  def index
    @spaces = Space.all
  end

  def show
    @space = Space.find_by slug: params[:slug]

    if (!@space)
      render 'spaces/not_found'
    end
  end

  def create
    @space = Space.new

    if @space.save
      redirect_to @space, notice: 'Space created. It will self-destruct in about 48 hours. Enjoy.'
    else
      render 'home/show'
    end
  end

  def destroy
  end
end

app/controllers/tokens_controller.rb
class TokensController < ApplicationController
  before_action :set_list, only: [:create]

  def edit
    @token = Token.find(params[:id])
  end

  def create
    @token = @list.tokens.new(token_params)
    respond_to do |format|
      if @token.save
        format.html { redirect_to list_path(@list), notice: 'Token created.' }
        format.json { render :show, status: :created, location: token_url(@token) }
      else
        format.html { render 'lists/show' }
        format.json { render json: @token.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @token = Token.find(params[:id])

    respond_to do |format|
      if @token.update(token_params)
        format.html { redirect_to @token.list, notice: 'Token updated.' }
        format.json { render :show, status: :ok, location: token_url(@token) }
      else
        format.html { render 'edit' }
      end
    end
  end

  def destroy
    @token = Token.find(params[:id])
    @token.destroy

    respond_to do |format|
      format.html { redirect_to @token.list, notice: 'Token deleted.' }
      format.json { head :no_content }
    end
  end

  private

    def set_list
      @list = List.find(params[:list_id])
    end

    def token_params
      params.require(:token).permit(:name, :value, :category_id, :list_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/spaces_helper.rb
module SpacesHelper
end

app/helpers/tokens_helper.rb
module TokensHelper
end

app/views/categories/_category.html.erb
<tr>
  <td><%= category.name %></td>
  <td><%= link_to 'Edit', edit_category_path(category) %></td>
  <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/_list.html.erb
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= render @categories %>
  </tbody>
</table>

app/views/categories/edit.html.erb
<h1>Edit Existing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back to all lists', lists_path %>

app/views/categories/new.html.erb
<h1>Add New Category</h1>
<p>The Elders have waited for this for a long time 🧓🏽👴🏾👵🏻</p>

<%= render 'form', category: @category %>

<%= link_to 'Back to all lists', lists_path %>

app/views/home/show.html.erb
<div class="home-page">
  <main class="home-page__container">
    <h1 class="home-page__title">TokenHub</h1>
    <%= form_with model: @space, local: true do |form| %>
    <%= form.submit class: "button" %>
    <% end %>
  </main>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar">
  <h3 class="navbar__title">TokenHub</h3>
</nav>

app/views/layouts/_notice.html.erb
<% if notice.present? %>
  <div class="notice">
    <div class="notice__container">
      <%= notice %>
    </div>
  </div>
<% end %>

<% if alert.present? %>
  <div class="notice notice--alert">
    <div class="notice__container">
      <%= alert %>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en-US">
  <head>
    <title>🦁 API Spike</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="application-layout">
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/notice' %>
    <div class="page-container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html lang="en-US">
  <head>
    <title>Welcome to Token Park</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="home-layout">
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_with(model: model, local: true, class: 'form') do |form| %>
  <% if list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
        <% list.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form__input">
    <%= form.label :name, class: 'form__label' %>
    <%= form.text_field :name, placeholder: 'Unicorn Tokens', class: 'form__field' %>
  </div>

  <%= form.submit nil, class: 'form__submit-button button' %>
<% end %>

app/views/lists/edit.html.erb
<div class="edit-list-page">
  <nav class="edit-list-page__back-link">
    <%= link_to 'Back to list', @list %>
  </nav>

  <h1 class="edit-list-page__title">Edit list</h1>

  <div class="edit-list-page__form">
    <%= render 'form', list: @list, model: @list %>
  </div>
</div>

app/views/lists/new.html.erb
<div class="new-list-page">
  <nav class="new-list-page__back-link">
    <%= link_to 'Back to lists', space_path(@list.space) %>
  </nav>

  <h1 class="new-list-page__title">Create List</h1>

  <div class="new-list-page__form">
    <%= render 'form', list: @list, model: [@space, @list] %>
  </div>
</div>

app/views/lists/show.html.erb
<div class="list-page">
  <nav class="list-page__back-link">
    <%= link_to 'Back to lists', space_path(@list.space) %>
  </nav>
  <header class="list-page__header">
    <h1 class="list-page__title"><%= @list.name %></h1>
    <p class="list-page__token-count">
      <%= @list.tokens.size %> <%= 'token'.pluralize @list.tokens.size %>
    </p>
    <div class="list-page__edit-name-pill">
      <div class="pill-actions">
        <%= link_to 'Edit name', edit_list_path(@list), class: 'pill-actions__item' %>
      </div>
    </div>
  </header>

  <div class="list-page__add-token-section">
    <h2 class="list-page__add-token-section-title">Create a new token</h2>
    <div class="list-page__add-token-form">
      <%= render 'tokens/form', token: [@list, @list.tokens.new] %>
    </div>
  </div>

  <div class="list-page__tokens-section">
    <% @groupedTokens.each do |categoryName, tokens| %>
      <div class="list-page__token-category">
        <h2 class="list-page__token-category-title"><%= categoryName %></h2>
        <div class="list-page__token-category-grid">
          <% tokens.each do |token| %>
            <div class="card">
              <%= render token %>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/other/404.html.erb
<h1>404 Not Found</h1>
<h2>Sorry</h2>

app/views/spaces/_space.html.erb
<div class="space-list-item">
  <p><%= link_to "Space ##{space.id}", space %></p>
</div>

app/views/spaces/index.html.erb
<div class="spaces-page">
  <h1>Spaces</h1>
  <div class="spaces-page__list">
    <%= render @spaces %>
  </div>
</div>

app/views/spaces/not_found.html.erb
<h1>Couldn’t find this space. Sorry, boo.</h1>

app/views/spaces/show.html.erb
<div class="space-page">

  <h2 class="space-page__title"><%= @space.slug %></h2>
  <% if @space.lists.empty? %>
    <p class="space-page__no-tokens-text">There are no token lists yet. Go ahead and create the first one.</p>
  <% else %>
    <ul class="space-page__list-of-lists">
      <% @space.lists.each do |list| %>
        <li class="space-page__list-item">
          <%= link_to list.name, list_path(list), class: 'space-page__list-item-link' %>
        </li>
      <% end %>
    </ul>
  <% end %>

  <div class="actions">
    <%= link_to 'Create list', new_space_list_path(@space), class: 'actions__item' %>
  </div>

</div>

app/views/tokens/_form.html.erb
<%= form_with model: token, local: true, class: 'form' do |form| %>
  <div class="form__input">
    <%= form.label :name, class: 'form__label' %><br>
    <%= form.text_field :name, class: 'form__field' %>
  </div>

  <div class="form__input">
    <%= form.label :value, class: 'form__label' %><br>
    <%= form.text_field :value, class: 'form__field' %>
  </div>

  <div class="form__input">
    <%= form.label :category_id, class: 'form__label' %><br>
    <%= form.collection_select(:category_id, Category.all, :id, :name, include_blank: 'No Category') %>
  </div>

  <%= form.submit nil, class: 'form__submit-button button' %>
<% end %>

app/views/tokens/_token.html.erb
<div class="token">
  <div class="token__content">
    <h3 class="token__value"><%= token.value %></h3>
    <p class="token__name"><%= token.name %></p>
  </div>
  <div class="pill-actions">
    <%= link_to 'Edit', edit_token_path(token), class: 'pill-actions__item' %>
    <%= link_to 'Delete', token,
                method: :delete, class: 'pill-actions__item' %>
  </div>
</div>

app/views/tokens/edit.html.erb
<!-- <h1>Editing Token</h1>

<%= render 'form', token: @token %>

<%= link_to 'Back to list', list_path(@token.list) %> -->

<div class="edit-token-page">
  <nav class="edit-token-page__back-link">
    <%= link_to 'Back to list', @token.list %>
  </nav>

  <h1 class="edit-token-page__title">Edit token</h1>

  <div class="edit-token-page__form">
    <%= render 'form', token: @token %>
  </div>
</div>

app/views/tokens/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tokens</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Value</th>
      <th>List</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tokens.each do |token| %>
      <tr>
        <td><%= token.name %></td>
        <td><%= token.value %></td>
        <td><%= token.list_id %></td>
        <td><%= link_to 'Show', token %></td>
        <td><%= link_to 'Edit', edit_token_path(token) %></td>
        <td><%= link_to 'Destroy', token, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Token', new_token_path %>

app/views/tokens/new.html.erb
<h1>New Token</h1>

<%= render 'form', token: @token %>

<%= link_to 'Back', tokens_path %>

app/views/tokens/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @token.name %>
</p>

<p>
  <strong>Value:</strong>
  <%= @token.value %>
</p>

<p>
  <strong>List:</strong>
  <%= @token.list_id %>
</p>

<%= link_to 'Edit', edit_token_path(@token) %> |
<%= link_to 'Back', tokens_path %>